# Generated by Django 5.1 on 2024-08-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='est_m_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_codigo', models.PositiveBigIntegerField()),
                ('em_codigo', models.CharField(max_length=100)),
                ('cl_codigo', models.CharField(max_length=100)),
                ('ci_fecha', models.DateField()),
                ('ci_hora', models.CharField(max_length=5)),
                ('ci_estado', models.BooleanField(default=True)),
                ('ci_nota', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='est_m_cita_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_codigo', models.PositiveBigIntegerField()),
                ('em_codigo', models.PositiveBigIntegerField()),
                ('cl_codigo', models.PositiveBigIntegerField()),
                ('ci_codigo', models.PositiveBigIntegerField()),
                ('se_codigo', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='est_m_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_codigo', models.PositiveBigIntegerField()),
                ('us_codigo', models.PositiveBigIntegerField()),
                ('cl_forma_pago', models.CharField(max_length=100)),
                ('cl_calificacion', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='est_m_emplado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_codigo', models.PositiveBigIntegerField()),
                ('us_codigo', models.PositiveBigIntegerField()),
                ('em_especialidad', models.CharField(max_length=100)),
                ('em_fecha_contrato', models.DateField()),
                ('em_hora_entrada', models.CharField(max_length=100)),
                ('em_hora_salida', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='est_m_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_codigo', models.PositiveBigIntegerField()),
                ('se_nombre', models.CharField(max_length=100)),
                ('se_descripcion', models.CharField(max_length=100)),
                ('se_duracion', models.PositiveBigIntegerField()),
                ('se_precio', models.CharField(max_length=100)),
                ('se_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='est_m_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_codigo', models.PositiveBigIntegerField()),
                ('us_cedula', models.CharField(max_length=10)),
                ('us_nombre', models.CharField(max_length=100)),
                ('us_apellido', models.CharField(max_length=100)),
                ('us_correo', models.CharField(max_length=100)),
                ('us_telefono', models.CharField(max_length=100)),
                ('us_clave', models.CharField(max_length=100)),
                ('ro_codigo', models.PositiveBigIntegerField()),
                ('us_estado', models.BooleanField(default=True)),
                ('us_comentarios', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='est_s_funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fu_codigo', models.PositiveBigIntegerField()),
                ('fu_descripcion', models.CharField(max_length=100)),
                ('fu_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='est_s_funcion_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_codigo', models.PositiveBigIntegerField()),
                ('fu_codigo', models.PositiveBigIntegerField()),
                ('ro_codigo', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='est_s_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_codigo', models.PositiveBigIntegerField()),
                ('ro_nombre', models.CharField(max_length=100)),
                ('ro_descripcion', models.CharField(max_length=100)),
                ('ro_estado', models.BooleanField(default=True)),
            ],
        ),
    ]
