# Generated by Django 5.1 on 2024-08-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='est_m_cita',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_m_cita_servicio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_m_cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_m_emplado',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_m_servicio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_m_usuario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_s_funcion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_s_funcion_rol',
            name='id',
        ),
        migrations.RemoveField(
            model_name='est_s_roles',
            name='id',
        ),
        migrations.AlterField(
            model_name='est_m_cita',
            name='ci_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_m_cita',
            name='ci_nota',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='est_m_cita_servicio',
            name='cs_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_m_cliente',
            name='cl_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_m_cliente',
            name='cl_forma_pago',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='est_m_emplado',
            name='em_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_m_emplado',
            name='em_especialidad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='est_m_emplado',
            name='em_fecha_contrato',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='est_m_servicio',
            name='se_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_m_servicio',
            name='se_descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='us_apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='us_cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='us_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='us_comentarios',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='us_correo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='us_nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='us_telefono',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='est_s_funcion',
            name='fu_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_s_funcion',
            name='fu_descripcion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='est_s_funcion_rol',
            name='fr_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_s_roles',
            name='ro_codigo',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='est_s_roles',
            name='ro_descripcion',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='est_s_roles',
            name='ro_nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
