# Generated by Django 5.1 on 2024-08-11 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_est_s_funcion_rol_fu_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='est_m_cita',
            name='em_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_emplado'),
        ),
        migrations.AlterField(
            model_name='est_m_cita_servicio',
            name='ci_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_cita'),
        ),
        migrations.AlterField(
            model_name='est_m_cita_servicio',
            name='cl_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_cliente'),
        ),
        migrations.AlterField(
            model_name='est_m_cita_servicio',
            name='em_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_emplado'),
        ),
        migrations.AlterField(
            model_name='est_m_cita_servicio',
            name='se_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_servicio'),
        ),
        migrations.AlterField(
            model_name='est_m_cliente',
            name='us_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_usuario'),
        ),
        migrations.AlterField(
            model_name='est_m_emplado',
            name='us_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_usuario'),
        ),
        migrations.AlterField(
            model_name='est_m_empleado_especialidad',
            name='em_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_emplado'),
        ),
        migrations.AlterField(
            model_name='est_m_empleado_especialidad',
            name='es_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_especialidad'),
        ),
        migrations.AlterField(
            model_name='est_m_servicio',
            name='ca_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_categoria'),
        ),
        migrations.AlterField(
            model_name='est_m_usuario',
            name='ro_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_s_roles'),
        ),
    ]
