# Generated by Django 5.1 on 2024-08-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_est_m_cita_em_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='est_m_cita',
            name='cl_codigo',
        ),
        migrations.RemoveField(
            model_name='est_m_cita',
            name='em_codigo',
        ),
        migrations.AddField(
            model_name='est_m_categoria',
            name='es_codigo',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
