# Generated by Django 5.1 on 2024-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_est_m_cita_cl_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='est_m_categoria',
            name='ca_imagen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
