# Generated by Django 5.1 on 2024-08-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_est_m_categoria_ca_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='est_m_categoria',
            name='es_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.est_m_especialidad'),
        ),
    ]
