# Generated by Django 5.1 on 2024-08-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_est_m_categoria_es_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='est_m_emplado',
            name='em_imagen',
            field=models.CharField(default='', max_length=100),
        ),
    ]
