# Generated by Django 5.1 on 2024-08-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_est_m_emplado_em_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='est_m_reserva',
            fields=[
                ('re_codigo', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('re_fecha', models.DateField()),
                ('re_estado', models.BooleanField(default=True)),
            ],
        ),
    ]
